# Generated by Django 5.1.6 on 2025-02-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('username', models.TextField(max_length=150)),
                ('profession', models.TextField(max_length=70)),
                ('description', models.TextField(max_length=333)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
