# Generated by Django 5.1.6 on 2025-02-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('name_coursec', models.TextField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('title', models.TextField(max_length=80)),
                ('suptitle', models.TextField(max_length=320)),
                ('info_course', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teachers', models.ManyToManyField(related_name='courses', to='team.team')),
            ],
        ),
    ]
